src/main/java/com/e_shopper/model/CartItem.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.e_shopper.model;

import com.e_shopper.beans.product;

/**
 *
 * @author User
 */
public class CartItem {
    private product prod;
    private int quantity;

    public CartItem() {
        this.quantity = 0 ;
    }

    public CartItem(product prod, int quantity) {
        this.prod = prod;
        this.quantity = quantity;
    }

    public product getProd() {
        return prod;
    }

    public void setProd(product prod) {
        this.prod = prod;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    public int getAmount(){
        return this.prod.getPro_price()*this.quantity;
    }
}

src/main/webapp/WEB-INF/jsp/cart.jsp
<%-- 
    Document   : cart
    Created on : Jul 6, 2017, 11:18:35 PM
    Author     : User
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<section class="main-content">				
    <div class="row">
        <div class="span9" style = "margin-left: 130px;">	
            <form class="form-inline" method="post" action="/e-shopper/cart">
                <h4 class="title"><span class="text"><strong>Giỏ Hàng của bán</strong></span></h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Xóa</th>
                            <th>Hình Sản Phẩm</th>
                            <th>Tên Sản Phẩm</th>
                            <th>Số Lượng</th>
                            <th>Giá</th>
                            <th>Tổng</th>
                        </tr>
                    </thead>
                    <tbody>
                        <c:forEach items="${cart}" var="item">
                            <tr>
                                <td>
                                    <input type="checkbox" value="${item.prod.pro_id}" name="remove">
                                </td>
                                <td><a href="productDetail?id=${item.prod.pro_id}"><img alt="" src="${item.prod.pro_img_link}"></a></td>
                                <td>${item.prod.pro_name}</td>
                                <td><input type="text" name="quantity" class="span1" value="${item.quantity}" required="" ></td>
                                <td>${item.prod.pro_price} VND</td>
                                <td>${item.getAmount()} VND</td>

                            </tr>
                        </c:forEach>

                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td><strong style="color:red">Thành Tiền</strong></td>
                            <td><strong>${amountTotal} VND</strong></td>
                        </tr>		  
                    </tbody>
                </table>
                
                <hr>
                <p class="cart-total right">
                    <strong>Tạm Tính</strong>: $${amountTotal}<br>
                    <strong>Thuế (-0.00)</strong>: 0.00 VND<br>
                    <strong>VAT (0.00%)</strong>: 0.00 VND<br>
                    <strong style="color:red">THÀNH TIỀN</strong>: ${amountTotal} VND<br>
                </p>
                <hr/>
                <input type="checkbox" checked="checked" name="remove" value="-100" style="visibility: hidden;"/>
                <p class="buttons center">				
                    <button class="btn" type="submit">Cập Nhật</button>
                    <button class="btn" type="button"><a style="color: #333" href="/e-shopper/">Tiếp tục mua hàng</a></button>
                    <button class="btn btn-inverse" type="button" id="checkout">
                        <a style="color: #fff"href="/e-shopper/checkout">Tiến hành đặt hàng</a>
                    </button>
                </p>			
            </form>
        </div>
    </div>
</section>	

src/main/webapp/WEB-INF/jsp/cart_top.jsp
<%-- 
    Document   : cart_top
    Created on : Jul 6, 2017, 11:19:35 PM
    Author     : User
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<section class="header_text sub">
    <img class="pageBanner" src="/e-shopper/assets/themes/images/pageBanner.png" alt="New products" >
    <h4><span>Giỏ hàng của bạn</span></h4>
</section>

src/main/webapp/WEB-INF/jsp/checkout.jsp
<%-- 
    Document   : checkout
    Created on : Jul 6, 2017, 9:07:35 PM
    Author     : User
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<section class="main-content">
    <div class="row">
        <div class="span12">
            <div class="accordion" id="accordion2">

                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="">Tài Khoản &amp; Chi tiết đặt hàng</a>
                    </div>
                    <div id="collapseTwo" class="accordion-body ">
                        <div class="accordion-inner">
                            <div class="row-fluid">
                                <div class="span6" style="">
                                    <h4>Your Personal Details</h4>
                                    <form method="post" action="/e-shopper/checkout">
                                        <div class="control-group">
                                            <label class="control-label"><span class="required">*</span><strong>Tên</strong></label>
                                            <div class="controls">
                                                <input type="text" placeholder="" required=""class="input-xlarge" name="name" 
                                                       value="${name}">
                                            </div>
                                            <c:choose>
                                                <c:when test="${nameVali==1}">
                                                    <div class="error" style="color: red">Vui lòng nhập đúng tên.</div>
                                                </c:when>
                                                <c:when test="${nameVali==2}">
                                                    <div class="error" style="color: red">Tên ít nhất phải từ 6 ký tự.</div>
                                                </c:when>
                                            </c:choose>
                                        </div>

                                        <div class="control-group">
                                            <label class="control-label"><span class="required">*</span><strong>Email Address</strong></label>
                                            <div class="controls">
                                                <input type="text" placeholder="" required="" class="input-xlarge" name="email" 
                                                       value="${email}" >
                                            </div>
                                            <c:choose>
                                                <c:when test="${emailVali==1}">
                                                    <div class="error"style="color: red">Vui lòng nhập chính xác địa chỉ email của bạn.</div>
                                                </c:when>
                                                <c:when test="${emailVali == 2}">
                                                    <div class="error"style="color: red">Địa chỉ bạn nhập vào chưa đúng định dạng email.</div>
                                                </c:when>
                                            </c:choose>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label"><span class="required">*</span><strong>Điện thoại</strong></label>
                                            <div class="controls">
                                                <input type="text" placeholder="" required=""class="input-xlarge" name="mobile"
                                                       value="${mobile}">
                                            </div>
                                            <c:choose>
                                                <c:when test="${mobileVali == 1}">
                                                    <div class="error"style="color: red">Vui lòng nhập chính xác Số điện thoại của bạn.</div>
                                                </c:when>
                                                <c:when test="${mobileVali == 2}">
                                                    <div class="error"style="color: red">Số điện thoại phải từ 8 số trở lên.</div>
                                                </c:when>
                                            </c:choose>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label"> <span class="required">*</span><strong>Thành Phố</strong></label>
                                            <div class="controls">
                                                <select name="province" class="input-xlarge">
                                                    <option value=""> --- Vui lòng chọn Thành Phố --- </option>
                                                    <option value="Ho Chi Minh">Ho Chi Minh</option>
                                                    <option value="Ha Noi">Ha Noi</option>
                                                    <option value="Da Nang">Da Nang</option>
                                                    <option value="Quy Nhon">Quy Nhon</option>
                                                </select>
                                            </div>
                                            <c:choose>
                                                <c:when test="${province eq ''}">
                                                    <div class="error"style="color: red">Chọn Quận/Huyện/Phường.</div>
                                                </c:when>
                                            </c:choose>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label"><span class="required">*</span> <strong>Quận/Huyện</strong></label>
                                            <div class="controls">
                                                <select name="district" class="input-xlarge">
                                                    <option value=""> --- Vui lòng chọn--- </option>
                                                    <option value="Quan a">Quận 1</option>
                                                    <option value="Hoan Kiem">Hoàn Kiếm</option>
                                                    <option value="Son Tra">Sơn Trà</option>
                                                    <option value="Ngo May">Ngô Mây</option>
                                                </select>
                                            </div>
                                            <c:choose>
                                                <c:when test="${district eq ''}">
                                                    <div class="error"style="color: red">Vui lòng chọn.</div>
                                                </c:when>
                                            </c:choose>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label"><span class="required">*</span><strong>Địa chỉ</strong></label>
                                            <div class="controls">
                                                <input type="text" required="" placeholder="" class="input-xlarge" name="address"
                                                       value="${address}">
                                            </div>
                                            <c:choose>
                                                <c:when test="${addressVali == 1}">
                                                    <div class="error"style="color: red">Vui lòng chọn địa chỉ.</div>
                                                </c:when>
                                                <c:when test="${addressVali ==2}">
                                                    <div class="error"style="color: red">Địa chỉ ít nhất 8 kí tự.</div>
                                                </c:when>
                                            </c:choose>
                                        </div>
                                        <button class="btn btn-inverse pull-left" type="submit">Đặt Hàng</button>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>				
        </div>
    </div>
</section>			

src/main/webapp/WEB-INF/jsp/checkout_top.jsp
<%-- 
    Document   : checkout_top
    Created on : Jul 6, 2017, 9:08:42 PM
    Author     : User
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<section class="header_text sub">
    <img class="pageBanner" src="/e-shopper/assets/themes/images/pageBanner.png" alt="New products" >
    <h4><span>Thông tin đặt hàng</span></h4>
</section>	

src/main/webapp/WEB-INF/jsp/home.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<section class="header_text">
</section>
<section class="main-content">
    <div class="row">
        <div class="span12">								
            <ul class="thumbnails listing-products">
                <c:forEach items="${proList}" var="prod" end="12" begin="0">
                    <li class="span3">
                        <div class="product-box">												
                            <a href="productDetail?id=${prod.pro_id}"><img alt="" src="${prod.pro_img_link}"></a><br/>
                            <a href="productDetail?id=${prod.pro_id}" class="title">${prod.pro_name}</a><br/>
                            <a href="#" class="category">${prod.pro_category}</a><br/>
                            <p class="price">${prod.pro_price} VND</p>
                        </div>
                    </li>
                </c:forEach>

            </ul>								
            <hr>
        </div>
        
    </div>
</section>

src/main/webapp/WEB-INF/jsp/login_top.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<section class="header_text sub">
    <img class="pageBanner" src="/e-shopper/assets/themes/images/pageBanner.png" alt="New products" >
    <h4><span>Đăng Nhập</span></h4>
</section>

src/main/webapp/WEB-INF/jsp/orderBooking.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@page import="java.util.Date"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<aside class="right-side">
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                <div class="panel">
                    <header class="panel-heading">
                        <c:choose>
                            <c:when test="${not empty date}">
                                <strong>Đơn ngày ${date}</strong>
                            </c:when>
                            <c:otherwise>
                                <strong>Unprocessed Invoices</strong>
                            </c:otherwise>
                        </c:choose>
                    </header>
                    <!-- <div class="box-header"> -->
                    <!-- <h3 class="box-title">Responsive Hover Table</h3> -->

                    <!-- </div> -->
                    <div class="panel-body table-responsive">
                        <div class="box-tools m-b-15">
                            <div class="input-group">
                                <form action="/e-shopper/admin/searchOrder" method="post">
                                    <input type="date" name="searchOrd" class="form-control input-sm pull-left date" style="width: 150px;" />
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-default" type="submit"><i class="fa fa-search"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <table class="table table-hover">
                            <tr>
                                <th>STT</th>
                                <th>Tên</th>
                                <th>Số điện thoại</th>
                                <th>Email</th>
                                <th>Địa chỉ</th>
                                <th>Sản Phẩm</th>
                                <th>Số lượng</th>
                                <th>Thành tiền</th>
                                <th>Ngày đặt</th>
                                <th></th>
                                <th></th>
                            </tr>
                            <%
                                int i = 1;
                            %>
                            <c:forEach items="${orderList}" var="order" >
                                <tr>
                                    <td><%
                                        out.print(i++);
                                        %></td>
                                    <td>${order.cus_name}</td>
                                    <td>${order.cus_phone}</td>
                                    <td>${order.cus_email}</td>
                                    <td>${order.cus_addr}</td>
                                    <td><a href="productDetail?id=${order.prod_id}">
                                            <img alt="" src="${order.prod_img_link}">
                                        </a>
                                        <br/>
                                <center><strong>${order.prod_name}</strong></center>
                                </td>
                                <td>${order.quantity}</td>
                                <td><strong></strong>${order.amount} VND</td>
                                <td>${order.ord_date}</td>
                                <td> <a href="/e-shopper/admin/confirmOder?ord_id=${order.ord_id}" data-toggle="modal" class="btn btn-xs btn-success" >
                                        Xác nhận
                                    </a>
                                </td>
                                <td>
                                    <a href="/e-shopper/admin/declineOrder?ord_id=${order.ord_id}" data-toggle="modal" class="btn btn-xs btn-warning">
                                        Từ chối đơn
                                    </a>
                                </td>
                                </tr>
                            </c:forEach>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div>
        </div>

    </section>
</aside>

src/main/webapp/WEB-INF/jsp/prodList_ad.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<style type="text/css">
    img{
        width: 55%;
        height: auto;
    }
</style>
<aside class="right-side">
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                <div class="panel">
                    <header class="panel-heading">
                        <strong>Danh sách sản phẩm</strong>
                    </header>
                    <!-- <div class="box-header"> -->
                    <!-- <h3 class="box-title">Responsive Hover Table</h3> -->

                    <!-- </div> -->
                    <div class="panel-body table-responsive">
                        <div class="box-tools m-b-15">
                            <div class="input-group">
                                <form action="/e-shopper/admin/searchProd" method="post">
                                    <input type="text" name="searchProd" class="form-control input-sm pull-left" style="width: 150px;" placeholder="Search product"/>
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-default" type="submit"><i class="fa fa-search"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <table class="table table-hover">
                            <tr>
                                <th>STT</th>
                                <th>Hình sản phẩm</th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Số lượng còn</th>
                                <th></th>
                                <th></th>
                            </tr>
                            <%
                                int i = 1;
                            %>
                            <c:forEach items="${proList}" var="prod" >
                                <tr>
                                    <td><%
                                        out.print(i++);
                                        %></td>
                                    <td><a href="productDetail?id=${prod.pro_id}">
                                            <img alt="" src="${prod.pro_img_link}">
                                        </a>
                                    </td>
                                    <td>${prod.pro_name}</td>
                                    <td><strong></strong>${prod.pro_price} VND</td>
                                    <td>${prod.pro_stock}</td>
                                    <td> <a href="/e-shopper/admin/editProd?pro_id=${prod.pro_id}" data-toggle="modal" class="btn btn-xs btn-warning" >
                                            Sửa
                                        </a>
                                    </td>
                                    <td>
                                        <a href="/e-shopper/admin/deleteProd?pro_id=${prod.pro_id}" data-toggle="modal" class="btn btn-xs btn-danger">
                                            Xóa
                                        </a>
                                    </td>
                                </tr>
                            </c:forEach>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div>
        </div>

    </section>
</aside>

src/main/webapp/WEB-INF/jsp/productDetail.jsp
<%-- 
    Document   : productDetail
    Created on : Jul 6, 2017, 8:55:36 PM
    Author     : User
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page import="com.e_shopper.beans.product"%>
<section class="main-content">				
    <div class="row">						
        <div class="span9">
            <div class="row">
                <div class="span4">
                    <a href="${prod.pro_img_link}" class="thumbnail" data-fancybox-group="group1" title="Description 1"><img alt="" src="${prod.pro_img_link}"></a>												
                    <ul class="thumbnails small">								
                        <li class="span1">
                            <a href="/e-shopper/assets/themes/images/ladies/2.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 2"><img src="/e-shopper/assets/themes/images/ladies/2.jpg" alt=""></a>
                        </li>								
                        <li class="span1">
                            <a href="/e-shopper/assets/themes/images/ladies/3.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 3"><img src="/e-shopper/assets/themes/images/ladies/3.jpg" alt=""></a>
                        </li>													
                        <li class="span1">
                            <a href="/e-shopper/assets/themes/images/ladies/4.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 4"><img src="/e-shopper/assets/themes/images/ladies/4.jpg" alt=""></a>
                        </li>
                        <li class="span1">
                            <a href="/e-shopper/assets/themes/images/ladies/5.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 5"><img src="/e-shopper/assets/themes/images/ladies/5.jpg" alt=""></a>
                        </li>
                    </ul>
                </div>
                <div class="span5">
                    <address>
                        <strong>Mã sản phẩm:</strong> <span>${prod.pro_id}</span><br>
                        <strong>Tên sản phẩm:</strong> <span style ="color:red">${prod.pro_name}</span><br>
                        <strong>Số lượng còn :</strong> <span>${prod.pro_stock}</span><br>								
                    </address>									
                    <h4><strong>Giá: ${prod.pro_price} VND</strong></h4>
                </div>
                <div class="span5">
                    <form class="form-inline" method="post" action="/e-shopper/cart?prod_id=${prod.pro_id}">
                        <label>Số lượng:</label>
                        <input type="text" name="quantity" class="span1" value="1" required="" >
                        <button class="btn btn-inverse" type="submit">Mua ngay</button>
                    </form>
                    
                </div>							
            </div>
            <div class="row">
                <div class="span9">
                    <ul class="nav nav-tabs" id="myTab">
                        <li class="active"><a href="#home">Mô Tả</a></li>
                        <li class=""><a href="#profile">Thông tin bổ sung</a></li>
                    </ul>							 
                    <div class="tab-content">
                        <div class="tab-pane active" id="home">${prod.pro_details}</div>
                        <div class="tab-pane" id="profile">
                            <table class="table table-striped shop_attributes">	
                                <tbody>
                                    <tr class="">
                                        <th>Size</th>
                                        <td>Large, Medium, Small, X-Large</td>
                                    </tr>		
                                    <tr class="alt">
                                        <th>Colour</th>
                                        <td>Orange, Yellow</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>							
                </div>						
                
        </div>
       
        </div>
    </div>
</section>			

<script>
    $(function () {
        $('#myTab a:first').tab('show');
        $('#myTab a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
        })
    })
    $(document).ready(function () {
        $('.thumbnail').fancybox({
            openEffect: 'none',
            closeEffect: 'none'
        });

        $('#myCarousel-2').carousel({
            interval: 2500
        });
    });
</script>

src/main/webapp/WEB-INF/jsp/productDetail_top.jsp
<%-- 
    Document   : productDetail_top
    Created on : Jul 6, 2017, 8:55:58 PM
    Author     : User
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<section class="header_text sub">
    <img class="pageBanner" src="/e-shopper/assets/themes/images/pageBanner.png" alt="New products" >
    <h4><span>Chi tiết Sản Phẩm</span></h4>
</section>

src/main/webapp/WEB-INF/jsp/productList_top.jsp
<%-- 
    Document   : productList_top
    Created on : Jul 6, 2017, 8:50:27 PM
    Author     : User
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<section class="header_text sub">
    <img class="pageBanner" src="/e-shopper/assets/themes/images/pageBanner.png" alt="New products" >
    <h4><span>Sản Phẩm</span></h4>
</section>

src/main/webapp/WEB-INF/jsp/successProcess.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<aside class="right-side">
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                <div class="panel">
                    <c:choose>
                         <c:when test="${succAddProd==1}">
                            <center>
                                <label class="control-label" style="font-size: 16px;color: green">Thêm sản phẩm thành công.</label>
                            </center>
                        </c:when>
                        <c:when test="${succDel==1}">
                            <center>
                                <label class="control-label" style="font-size: 16px;color: green">Xóa sản phẩm thành công.</label>
                            </center>
                        </c:when>
						<c:when test="${succEdit==1}">
                            <center>
                                <label class="control-label" style="font-size: 16px;color: green">Sản phẩm đã được cập nhật.</label>
                            </center>
                        </c:when>
						<c:when test="${succConf ==1}">
                            <center>
                                <label class="control-label" style="font-size: 16px;color: green">Đã xác nhận.</label>
                            </center>
                        </c:when>
						<c:when test="${succDecl==1}">
                            <center>
                                <label class="control-label" style="font-size: 16px;color: green">Đã hủy đơn hàng.</label>
                            </center>
                        </c:when>
                    </c:choose>
                </div>
            </div>
        </div>
    </section>
</aside>